# Generated by Django 3.0.8 on 2020-07-14 15:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralNetworks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creator', models.TextField()),
                ('neuron_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('activation_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
            ],
        ),
    ]
