# Generated by Django 3.0.8 on 2020-07-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuralnetworks',
            name='problem',
            field=models.TextField(default=''),
        ),
    ]
