# Generated by Django 3.0.8 on 2020-07-15 11:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_neuralnetworks_mse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuralnetworks',
            name='activation_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1000, null=True), blank=True, null=True, size=None),
        ),
    ]
