# Generated by Django 3.0.8 on 2020-10-04 20:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20200715_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('xplot', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('yplot', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('yhatplot', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('nnb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.NeuralNetworks')),
            ],
        ),
    ]
