# Generated by Django 3.0.8 on 2020-10-06 20:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20201004_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphs',
            name='initial_yhatplot',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
