# Generated by Django 3.0.8 on 2020-10-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_graphs_initial_xplot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphs',
            old_name='id',
            new_name='idg',
        ),
    ]
