# Generated by Django 3.0.8 on 2020-10-08 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20201008_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphs',
            old_name='idg',
            new_name='id',
        ),
    ]
